### PR TITLE
fix: path completion

### PR DESCRIPTION
**Pull request by liu-lihao**

### CODE REVIEW

**Comment by liu-lihao** [comment]
#4

**Comment by walpolea** [comment]
Will this pr get merged? Could really use this path fix! @egoist

**Comment by liu-lihao** [comment]
> Will this pr get merged? Could really use this path fix! @egoist

yes

**Review by Akryum — CHANGES_REQUESTED** [review]
You should probably revert the unrelated changes such as package.json and pnpm-lock.yaml

I tried the fix and it's working great. :+1:

**Comment by liu-lihao** [comment]
> You should probably revert the unrelated changes such as package.json and pnpm-lock.yaml
> 
> I tried the fix and it's working great. 👍

Because I need `build.initialOptions` above 0.9.6

https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#096

**Pull request merged**
